# Markov Transition Matrix between Delinquency Statuses

This technical report is oriented to calculate the probability matrix in the "actual" dataset to see the next month distribution. The following transition matrices were taken in consideration: 

- Transition Matrix for all loans in a single markov chain in the full dataset.
- Transition Matrix for a markov chain per loan in the full dataset.
- Transition Matrix per Loan without consecutive Paid-Off status' in the full dataset.
- Transition Matrix per Loan without invalid transitions and consecutive Paid-Off status for Subprime, Prime and full dataset.
- Transition Matrix for unknown type of loans. 

This is an investigation based on the actual data, not related to the training model shown before. There are some open questions for further discussion.

In [2]:
import sys
import os
import pandas as pd
from pathlib import Path
import numpy as np
import datetime


nb_dir = os.path.join(Path(os.getcwd()).parents[0], 'src', 'data')
pdata_dir = os.path.join(Path(os.getcwd()).parents[0], 'data', 'processed')
if nb_dir not in sys.path:
    sys.path.insert(0, nb_dir)
# print(sys.path)
import make_dataset as md
import build_data as bd
import get_raw_data as grd
import features_selection as fs

models_dir = os.path.join(Path(os.getcwd()).parents[0], 'src', 'models')
if models_dir not in sys.path:
    sys.path.insert(0, models_dir)
import nn_real as nn

FLAGS Namespace(data_dir='/input_data', dropout_keep=0.5, epoch_num=1000, learning_rate=0.1, logdir='/real_summaries', n_hidden=3, s_hidden=[200, 140, 140], stratified_flag=False, xla=True)
UNPARSED ['-f', 'C:\\Users\\sandr\\AppData\\Roaming\\jupyter\\runtime\\kernel-fce48441-e41e-4003-ae75-df316d73158d.json']

## Original Feeding Set

In [2]:
all_data = grd.read_df(45)
print(all_data.shape)
pd.options.display.max_columns = 1500
all_data.head(15)

2018-04-05 14:25:33,695 - read_df - INFO - merged shape:(4055501, 195)
2018-04-05 14:26:28,715 - read_df - INFO - dynamic shape:(4056947, 34) static shape:(67637, 164) unemployment shape: (17212, 3) merged shape: (4054864, 196)

(4054864, 196)

,LOAN_ID,ASOFMONTH,MBA_DAYS_DELINQUENT,CURRENT_INTEREST_RATE,LLMA2_CURRENT_INTEREST_SPREAD,LOANAGE,CURRENT_BALANCE,SCHEDULED_PRINCIPAL,SCHEDULED_MONTHLY_PANDI,LLMA2_HIST_LAST_12_MONTHS_MIS,LLMA2_C_IN_LAST_12_MONTHS,LLMA2_30_IN_LAST_12_MONTHS,LLMA2_60_IN_LAST_12_MONTHS,LLMA2_90_IN_LAST_12_MONTHS,LLMA2_FC_IN_LAST_12_MONTHS,LLMA2_REO_IN_LAST_12_MONTHS,YEAR,MONTH,TIME,CURRENT_INTEREST_RATE_nan,MBA_DAYS_DELINQUENT_nan,SCHEDULED_MONTHLY_PANDI_nan,SCHEDULED_PRINCIPAL_nan,MBA_DELINQUENCY_STATUS_next,MBA_DELINQUENCY_STATUS_0,MBA_DELINQUENCY_STATUS_3,MBA_DELINQUENCY_STATUS_6,MBA_DELINQUENCY_STATUS_9,MBA_DELINQUENCY_STATUS_C,MBA_DELINQUENCY_STATUS_F,MBA_DELINQUENCY_STATUS_R,CURRENT_INVESTOR_CODE_253,MBA_DELINQUENCY_STATUS,FICO_SCORE_ORIGINATION,INITIAL_INTEREST_RATE,ORIGINAL_LTV,ORIGINAL_BALANCE,BACKEND_RATIO,SALE_PRICE,NUMBER_OF_UNITS,LLMA2_APPVAL_LT_SALEPRICE,LLMA2_ORIG_RATE_SPREAD,MARGIN,PERIODIC_RATE_CAP,PERIODIC_RATE_FLOOR,LIFETIME_RATE_CAP,LIFETIME_RATE_FLOOR,RATE_RESET_FREQUENCY,PAY_RESET_FREQUENCY,FIRST_RATE_RESET_PERIOD,LLMA2_PRIME,LLMA2_SUBPRIME,BACKEND_RATIO_nan,FIRST_RATE_RESET_PERIOD_nan,LIFETIME_RATE_CAP_nan,LIFETIME_RATE_FLOOR_nan,MARGIN_nan,PAY_RESET_FREQUENCY_nan,PERIODIC_RATE_CAP_nan,PERIODIC_RATE_FLOOR_nan,RATE_RESET_FREQUENCY_nan,SALE_PRICE_nan,ORIGINAL_TERM_180,ORIGINAL_TERM_240,ORIGINAL_TERM_360,LLMA2_VINTAGE_2005,BUYDOWN_FLAG_N,BUYDOWN_FLAG_U,BUYDOWN_FLAG_Y,NEGATIVE_AMORTIZATION_FLAG_N,NEGATIVE_AMORTIZATION_FLAG_U,NEGATIVE_AMORTIZATION_FLAG_Y,PREPAY_PENALTY_FLAG_N,PREPAY_PENALTY_FLAG_U,PREPAY_PENALTY_FLAG_Y,OCCUPANCY_TYPE_1,OCCUPANCY_TYPE_2,OCCUPANCY_TYPE_3,OCCUPANCY_TYPE_U,PRODUCT_TYPE_10,PRODUCT_TYPE_20,PRODUCT_TYPE_30,PRODUCT_TYPE_50,PRODUCT_TYPE_51,PRODUCT_TYPE_52,PRODUCT_TYPE_54,PRODUCT_TYPE_5A,PRODUCT_TYPE_5Z,PRODUCT_TYPE_60,PRODUCT_TYPE_63,PRODUCT_TYPE_70,PRODUCT_TYPE_80,PRODUCT_TYPE_81,PRODUCT_TYPE_82,PRODUCT_TYPE_83,PRODUCT_TYPE_84,PRODUCT_TYPE_8Z,PRODUCT_TYPE_U,LOAN_PURPOSE_1,LOAN_PURPOSE_2,LOAN_PURPOSE_3,LOAN_PURPOSE_5,LOAN_PURPOSE_6,LOAN_PURPOSE_7,LOAN_PURPOSE_8,LOAN_PURPOSE_9,LOAN_PURPOSE_B,LOAN_PURPOSE_U,DOCUMENTATION_TYPE_1,DOCUMENTATION_TYPE_2,DOCUMENTATION_TYPE_3,DOCUMENTATION_TYPE_U,CHANNEL_1,CHANNEL_2,CHANNEL_3,CHANNEL_4,CHANNEL_7,CHANNEL_8,CHANNEL_9,CHANNEL_A,CHANNEL_C,CHANNEL_D,CHANNEL_U,LOAN_TYPE_1,LOAN_TYPE_2,LOAN_TYPE_3,LOAN_TYPE_4,LOAN_TYPE_U,IO_FLAG_N,IO_FLAG_U,IO_FLAG_Y,CONVERTIBLE_FLAG_N,CONVERTIBLE_FLAG_U,CONVERTIBLE_FLAG_Y,POOL_INSURANCE_FLAG_N,POOL_INSURANCE_FLAG_U,POOL_INSURANCE_FLAG_Y,STATE_AE,STATE_AK,STATE_AL,STATE_AP,STATE_AR,STATE_AZ,STATE_CA,STATE_CO,STATE_CT,STATE_DC,STATE_DE,STATE_FL,STATE_GA,STATE_GU,STATE_HI,STATE_IA,STATE_ID,STATE_IL,STATE_IN,STATE_KS,STATE_KY,STATE_LA,STATE_MA,STATE_MD,STATE_ME,STATE_MI,STATE_MN,STATE_MO,STATE_MS,STATE_MT,STATE_NC,STATE_ND,STATE_NE,STATE_NH,STATE_NJ,STATE_NM,STATE_NN,STATE_NV,STATE_NY,STATE_OH,STATE_OK,STATE_OR,STATE_PA,STATE_PR,STATE_RI,STATE_SC,STATE_SD,STATE_TN,STATE_TX,STATE_UT,STATE_VA,STATE_VI,STATE_VT,STATE_WA,STATE_WI,STATE_WV,STATE_WY,STATE,UR
0,1152309363,2005-02-01,0,5.375,-0.255,1,179000.000000,0.000000,1002.349976,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,752.0,5.375,76.169998,179000.0,33.369999,0.0,1,0.0,-0.335,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
1,1152317734,2005-02-01,0,5.375,-0.255,1,150300.000000,0.000000,673.219971,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,706.0,5.375,79.940002,150300.0,24.030001,0.0,1,0.0,-0.335,0.0,2.0,3.375,6.0,0.0,12.0,0.0,36.0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,1,1,0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
2,1152382198,2005-02-01,0,6.500,0.870,71,140005.468750,203.009995,961.380005,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,556.0,6.500,90.000000,152100.0,0.000000,169000.0,1,0.0,0.790,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
3,1152396113,2005-02-01,0,5.500,-0.130,23,161749.593750,737.570007,1478.930054,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,767.0,5.500,31.200001,181000.0,0.000000,0.0,1,0.0,-0.210,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
4,1152400303,2005-02-01,0,4.750,-0.880,18,184149.234375,826.739990,1555.670044,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,736.0,4.750,69.440002,200000.0,0.000000,0.0,1,0.0,-0.960,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
5,1152400829,2005-02-01,0,4.000,-1.630,20,248959.078125,397.089996,1226.959961,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,600.0,4.000,77.639999,257000.0,0.000000,0.0,1,0.0,-1.710,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,1,1,1,1,0,0,1,1,0,1,1,0,0,1,1,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
6,1152379863,2005-02-01,0,6.875,1.245,81,28914.289062,217.839996,383.500000,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,766.0,6.875,34.000000,43000.0,0.000000,0.0,1,0.0,1.165,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
7,1152379997,2005-02-01,0,7.125,1.495,81,49848.000000,81.309998,377.290009,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,640.0,7.125,80.000000,56000.0,0.000000,70000.0,1,0.0,1.415,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
8,1152380404,2005-02-01,0,7.000,1.370,79,84379.187500,166.429993,658.650024,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,634.0,7.000,71.000000,99000.0,0.000000,0.0,1,0.0,1.290,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
9,1152404341,2005-02-01,0,5.000,-0.630,19,39647.539062,174.850006,340.049988,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,672.0,5.000,45.259998,43000.0,0.000000,0.0,1,0.0,-0.710,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
10,1152394137,2005-02-01,0,6.000,0.370,24,243670.515625,280.519989,1498.880005,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,789.0,6.000,70.220001,250000.0,0.000000,0.0,1,0.0,0.290,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
11,1152394290,2005-02-01,0,5.250,-0.380,25,134901.718750,615.619995,1205.819946,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,772.0,5.250,38.790001,150000.0,0.000000,386687.0,1,0.0,-0.460,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
12,1152395588,2005-02-01,0,5.250,-0.380,24,203992.828125,361.040009,1253.510010,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,783.0,5.250,78.269997,227000.0,0.000000,0.0,1,0.0,-0.460,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
13,1152396423,2005-02-01,0,5.625,-0.005,23,267543.062500,328.950012,1583.060059,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,749.0,5.625,94.989998,275000.0,0.000000,289500.0,1,0.0,-0.085,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2
14,1152399007,2005-02-01,0,5.250,-0.380,21,144885.546875,674.840027,1308.719971,0,1,0,0,0,0,0,2005,2,421,0,0,0,0,C,0,0,0,0,1,0,0,1,C,735.0,5.250,66.440002,162800.0,0.000000,0.0,1,0.0,-0.460,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MN,4.2

## Ordering the Original Dataset
Ordering the dataset by ascending 'LOAN_ID' and 'ASOFMONTH' to count the transition states adequately.

In [3]:
all_data = all_data.sort_values(['LOAN_ID', 'ASOFMONTH'], ascending=[1, 1])
all_data.head(15)
all_data[['LOAN_ID', 'ASOFMONTH', 'MBA_DELINQUENCY_STATUS_next']]

            LOAN_ID  ASOFMONTH MBA_DELINQUENCY_STATUS_next
3548663   131175200 2005-10-01                           3
3549190   131175200 2005-11-01                           6
3548834   131175200 2005-12-01                           F
3549381   131175200 2006-01-01                           F
3549637   131175200 2006-02-01                           9
3550739   131175200 2006-03-01                           9
3549904   131175200 2006-04-01                           0
1657429   217010733 2011-03-01                           C
1657755   217010733 2011-04-01                           C
1658074   217010733 2011-05-01                           C
1658388   217010733 2011-06-01                           C
1659817   217010733 2011-07-01                           C
1660108   217010733 2011-08-01                           C
1658675   217010733 2011-09-01                           C
1658958   217010733 2011-10-01                           C
1659235   217010733 2011-11-01                           C
1659507   217010733 2011-12-01                           C
1661680   217010733 2012-01-01                           C
1660904   217010733 2012-02-01                           C
1660364   217010733 2012-03-01                           C
1660631   217010733 2012-04-01                           C
1661164   217010733 2012-05-01                           C
1661408   217010733 2012-06-01                           C
1661906   217010733 2012-07-01                           C
1662143   217010733 2012-08-01                           C
1662375   217010733 2012-09-01                           C
1662605   217010733 2012-10-01                           C
1662833   217010733 2012-11-01                           C
1663079   217010733 2012-12-01                           C
1663322   217010733 2013-01-01                           C
...             ...        ...                         ...
3834281  1243775877 2014-07-01                           C
3833750  1243775877 2014-08-01                           C
3834011  1243775877 2014-09-01                           C
3834542  1243775877 2014-10-01                           C
3834802  1243775877 2014-11-01                           C
3149484  1243775964 2012-11-01                           3
3149813  1243775964 2012-12-01                           3
3150138  1243775964 2013-01-01                           3
3151014  1243775964 2013-02-01                           3
3150421  1243775964 2013-03-01                           3
3150692  1243775964 2013-04-01                           3
3151534  1243775964 2013-05-01                           3
3151242  1243775964 2013-06-01                           3
3152041  1243775964 2013-07-01                           6
3151779  1243775964 2013-08-01                           6
3152549  1243775964 2013-09-01                           6
3153054  1243775964 2013-10-01                           9
3152290  1243775964 2013-11-01                           3
3152800  1243775964 2013-12-01                           3
3153550  1243775964 2014-01-01                           3
3153295  1243775964 2014-02-01                           3
3153797  1243775964 2014-03-01                           3
3154037  1243775964 2014-04-01                           C
3154277  1243775964 2014-05-01                           C
3154484  1243775964 2014-06-01                           C
3155089  1243775964 2014-07-01                           C
3154688  1243775964 2014-08-01                           C
3155289  1243775964 2014-09-01                           C
3154886  1243775964 2014-10-01                           C
3155487  1243775964 2014-11-01                           C

[4054864 rows x 3 columns]

## Extracting and Reformatting the Original labels

In [4]:
labels = bd.extract_numeric_labels(all_data, label_column='MBA_DELINQUENCY_STATUS_next')
all_data['MBA_DELINQUENCY_STATUS_next'] = labels

2018-04-05 14:30:05,297 - extract_numeric_labels - INFO - mapped labels: {'0': 0, '3': 1, '6': 2, '9': 3, 'C': 4, 'F': 5, 'R': 6}
2018-04-05 14:30:10,051 - extract_numeric_labels - INFO - ...Labels extracted from Dataset...
2018-04-05 14:30:10,054 - extract_numeric_labels - INFO - Size of the dataset after extract_labels:(4054864, 195)

In [36]:
display(labels)

3548663    1
3549190    2
3548834    5
3549381    5
3549637    3
3550739    3
3549904    0
1657429    4
1657755    4
1658074    4
1658388    4
1659817    4
1660108    4
1658675    4
1658958    4
1659235    4
1659507    4
1661680    4
1660904    4
1660364    4
1660631    4
1661164    4
1661408    4
1661906    4
1662143    4
1662375    4
1662605    4
1662833    4
1663079    4
1663322    4
          ..
3834281    4
3833750    4
3834011    4
3834542    4
3834802    4
3149484    1
3149813    1
3150138    1
3151014    1
3150421    1
3150692    1
3151534    1
3151242    1
3152041    2
3151779    2
3152549    2
3153054    3
3152290    1
3152800    1
3153550    1
3153295    1
3153797    1
3154037    4
3154277    4
3154484    4
3155089    4
3154688    4
3155289    4
3154886    4
3155487    4
Name: MBA_DELINQUENCY_STATUS_next, Length: 4054864, dtype: int64

## Transitions between statuses
From Paper (Sirignano et. al, 2017): 

"A mortgage is determined to be 1 month delinquent if no payment has been made by the last day of the month 
and the payment was due on the ﬁrst day of the month." 

"The transition matrices highlight that mortgages frequently transition back and forth between current and any other delinquency states. Disruptions in cashﬂow to the lender or servicer are common due to the mortgage being behind payment. Similarly, even loans that are extremely delinquent may return to current; the transition from foreclosed back to current is actually a relatively frequent occurrence. A foreclosure could get cured via paying the outstanding balance, there could be a pre-auction sale that covers all or some of the amount outstanding, or there could be a sale at the foreclosure auction that covers all or some of the amount outstanding. Any of these will register as a foreclosure to paid oﬀ transition. Mortgages can also transition directly from current, 30 days delinquent, 60 days delinquent, or 90+ days delinquent to REO via a 'deed in lieu of foreclosure' ".

The transition matrix calculation depends on not only the next status but also the next month. If certain ordered records for a loan are not consecutive in months, these transitions will not be considered in the calculation.

In [6]:
def transition_matrix(M, data):    
    # np.dstack((arr_a, arr_b)) # doesn't work
    transition_chain = np.array(list(zip(data['MBA_DELINQUENCY_STATUS_next'],data['MBA_DELINQUENCY_STATUS_next'][1:])))
    date_diff = (data[['ASOFMONTH']].diff() <= datetime.timedelta(days=31)).values.ravel()
    allowed_transitions = transition_chain[date_diff[1:]] 
    
    for z in range(0, len(allowed_transitions)):        
        i, j = allowed_transitions[z]        
        M[i][j] += 1                      

def probabilities_matrix(M):    
    for row in M:
        s = sum(row)
        if s > 0:
            row[:] = [f/s for f in row]

## Transition Matrix for all loans in a single markov chain
This function considers all original labels in a single markov chain and then calculates the transitions between states.

In [7]:
def markov_tmatrix_all_loans(data):
    n = 1+ max(data['MBA_DELINQUENCY_STATUS_next']) #number of statuses
    M = [[0]*n for _ in range(n)]
    transition_matrix(M, data)
    return M

## Transition Matrix - all Loans
The rows are the current status and the columns is the next month status according the dictionary: {'0': 0, '3': 1, '6': 2, '9': 3, 'C': 4, 'F': 5, 'R': 6}.

In [11]:
M = markov_tmatrix_all_loans(all_data)
display('Transition Matrix - all Loans')
display(M)

'Transition Matrix - all Loans'

[[223909, 554, 70, 98, 37687, 117, 35],
 [655, 33523, 16243, 127, 27056, 23, 6],
 [168, 3750, 9316, 10443, 2899, 802, 2],
 [1326, 802, 1416, 51088, 3399, 8114, 327],
 [34414, 38893, 273, 200, 3465537, 132, 42],
 [1305, 126, 66, 4103, 1841, 58488, 1722],
 [374, 21, 1, 475, 1181, 83, 7935]]

In [12]:
display('Probabilities Matrix - all Loans')
probabilities_matrix(M)
for row in M: print(' '.join('{0:.3f}'.format(x) for x in row))

'Probabilities Matrix - all Loans'

0.853 0.002 0.000 0.000 0.144 0.000 0.000
0.008 0.432 0.209 0.002 0.349 0.000 0.000
0.006 0.137 0.340 0.381 0.106 0.029 0.000
0.020 0.012 0.021 0.769 0.051 0.122 0.005
0.010 0.011 0.000 0.000 0.979 0.000 0.000
0.019 0.002 0.001 0.061 0.027 0.865 0.025
0.037 0.002 0.000 0.047 0.117 0.008 0.788

## Transition Matrix for a markov chain per loan
Taking into consideration all the records grouped by loan, so it does not consider spurious states: false states between different loans and loans with a single record.

In [7]:
def markov_tmatrix_per_loan(data):
    n = 1+ max(data['MBA_DELINQUENCY_STATUS_next']) # number of states
    M = [[0]*n for _ in range(n)]
    
    groups = data[['LOAN_ID', 'ASOFMONTH', 'MBA_DELINQUENCY_STATUS_next']].groupby(['LOAN_ID'])
    for name, group in groups: 
        group = group.sort_values(by=['ASOFMONTH'], ascending=[1])            
        transition_matrix(M, group)    
    return M

In [14]:
M = markov_tmatrix_per_loan(all_data)
display ('Transition Matrix per Loan')
display(M)

'Transition Matrix per Loan'

[[223031, 1, 0, 6, 4, 9, 5],
 [637, 33504, 16238, 119, 26030, 13, 2],
 [163, 3743, 9316, 10443, 2558, 798, 1],
 [1312, 788, 1415, 51078, 2701, 8107, 327],
 [34142, 38542, 206, 66, 3442966, 14, 8],
 [1294, 112, 63, 4093, 896, 58475, 1720],
 [368, 3, 0, 468, 9, 72, 7916]]

In [15]:
display('Probabilities Matrix per Loan')
probabilities_matrix(M)
for row in M: print(' '.join('{0:.3f}'.format(x) for x in row))

'Probabilities Matrix per Loan'

1.000 0.000 0.000 0.000 0.000 0.000 0.000
0.008 0.438 0.212 0.002 0.340 0.000 0.000
0.006 0.139 0.345 0.386 0.095 0.030 0.000
0.020 0.012 0.022 0.777 0.041 0.123 0.005
0.010 0.011 0.000 0.000 0.979 0.000 0.000
0.019 0.002 0.001 0.061 0.013 0.877 0.026
0.042 0.000 0.000 0.053 0.001 0.008 0.896

These matrices per loan are more realistic than the previous calculated matrices. However, there are inusual records when the current status is 0-'Paid-Off' and the next status is 0-'Paid-Off' as well. The same occurs in other states, it seems the dataset exhibits "invalid transitions".

## Delinquency statuses per Loan
To see how many records there are by loan, the full dataset was grouped by 'LOAN_ID', MBA_DELINQUENCY_STATUS_next'.

In [38]:
delinquencies = all_data[['LOAN_ID', 'MBA_DELINQUENCY_STATUS_next', 'ASOFMONTH']].groupby(['LOAN_ID', 'MBA_DELINQUENCY_STATUS_next'], as_index=False).count().sort_values(by=['LOAN_ID', 'MBA_DELINQUENCY_STATUS_next', 'ASOFMONTH'])
display(delinquencies)

           LOAN_ID  MBA_DELINQUENCY_STATUS_next  ASOFMONTH
0        131175200                            0          1
1        131175200                            1          1
2        131175200                            2          1
3        131175200                            3          2
4        131175200                            5          2
5        217010733                            4         45
6        217166158                            0         60
7        217236823                            4          3
8        217237944                            4          2
9        217238108                            4          3
10       217238606                            4          3
11       217241915                            4          3
12       217322232                            0         45
13       217644570                            4          1
14       217647229                            4          1
15       217850966                            4         39
16       217858165                            0         12
17       217858165                            4          7
18       217861385                            0          2
19       217861385                            1          4
20       217861385                            2          2
21       217861385                            3          5
22       217861385                            4         22
23       217861385                            5          4
24       217861468                            0          7
25       217861468                            1          1
26       217861468                            4         31
27       217861605                            1          1
28       217861605                            2          1
29       217861605                            3         19
...            ...                          ...        ...
148275  1243373479                            4         19
148276  1243377661                            1          9
148277  1243377661                            2          5
148278  1243377661                            4         11
148279  1243620449                            4         25
148280  1243620450                            4         25
148281  1243620532                            4         25
148282  1243620559                            0          1
148283  1243620559                            4         13
148284  1243620606                            0          1
148285  1243620606                            6          6
148286  1243620683                            0          1
148287  1243620683                            4          6
148288  1243620723                            1          1
148289  1243620723                            4         24
148290  1243620733                            0          1
148291  1243620733                            4          6
148292  1243620758                            0          1
148293  1243620758                            4         14
148294  1243620781                            1         10
148295  1243620781                            4         15
148296  1243623593                            4         25
148297  1243775687                            1          3
148298  1243775687                            2          2
148299  1243775687                            4         20
148300  1243775877                            4         25
148301  1243775964                            1         13
148302  1243775964                            2          3
148303  1243775964                            3          1
148304  1243775964                            4          8

[148305 rows x 3 columns]

Number of Loans per Delinquency Status.

In [57]:
delinquencies[['MBA_DELINQUENCY_STATUS_next', 'ASOFMONTH']].groupby('MBA_DELINQUENCY_STATUS_next').count()

                             ASOFMONTH
MBA_DELINQUENCY_STATUS_next
0                                39546
1                                16400
2                                 9573
3                                 8350
4                                65753
5                                 6499
6                                 2184

Number of Loan Monthly Payments per Delinquency Status.

In [58]:
delinquencies[['MBA_DELINQUENCY_STATUS_next', 'ASOFMONTH']].groupby('MBA_DELINQUENCY_STATUS_next').sum()

                             ASOFMONTH
MBA_DELINQUENCY_STATUS_next
0                               264639
1                                77705
2                                27400
3                                66621
4                              3540453
5                                67830
6                                10216

## Delinquency 0 (Paid-Off)
There are loans with several records that have delinquency states in 0-'Paid Off' at the end of its Markov Chain. 
It is interesting to see the number of consecutive records in 0-'Paid Off' status inside each Loan Markov chain.

##### Number of 0-'Pay-Off' Delinquencies per Loan

In [59]:
delinquency_0 = delinquencies[delinquencies.MBA_DELINQUENCY_STATUS_next==0].sort_values(by=['ASOFMONTH', 'LOAN_ID'])
display (delinquency_0)

           LOAN_ID  MBA_DELINQUENCY_STATUS_next  ASOFMONTH
0        131175200                            0          1
36       218036307                            0          1
107      218047831                            0          1
228      218087675                            0          1
232      218088688                            0          1
265      218519514                            0          1
295      218845444                            0          1
382      219145330                            0          1
442      219412986                            0          1
444      219413979                            0          1
446      219414358                            0          1
517      219908710                            0          1
521      219909337                            0          1
525      219909997                            0          1
546      219914691                            0          1
557      220142016                            0          1
559      220142204                            0          1
569      220143252                            0          1
572      220292752                            0          1
574      220293314                            0          1
596      220302093                            0          1
632      223603381                            0          1
636      223603499                            0          1
653      223603725                            0          1
909      227095472                            0          1
1507     227514701                            0          1
1575     227559117                            0          1
1659     227809845                            0          1
1778     227884317                            0          1
1798     227885108                            0          1
...            ...                          ...        ...
85146   1159418762                            0         60
91039   1159750587                            0         60
91978   1159784433                            0         60
98663   1160096529                            0         60
104972  1160347371                            0         60
105249  1160359487                            0         60
105514  1160369917                            0         60
106332  1160402007                            0         60
106647  1160411239                            0         60
109494  1160701880                            0         60
109645  1160754059                            0         60
109707  1160838471                            0         60
111501  1161042769                            0         60
112440  1161080669                            0         60
120078  1161872313                            0         60
37463   1154273003                            0         61
47383   1156900091                            0         61
57028   1157429803                            0         61
84599   1159397784                            0         61
98691   1160097733                            0         61
111512  1161043301                            0         61
111968  1161060908                            0         61
112195  1161069414                            0         61
67011   1158585288                            0         62
13613   1152863990                            0         64
142074  1216206664                            0         64
66802   1158576589                            0         65
86466   1159506184                            0         67
118817  1161340009                            0         67
104282  1160318794                            0         69

[39546 rows x 3 columns]

##### Showing all loans with 0-'Paid-Off' delinquencies  above 3 (Sample)

In [61]:
d = delinquencies[(delinquencies['ASOFMONTH'] > 3) & (delinquencies['MBA_DELINQUENCY_STATUS_next']==0)]
data_0 = all_data[all_data['LOAN_ID'].isin(d.LOAN_ID)][['LOAN_ID', 'ASOFMONTH', 'MBA_DELINQUENCY_STATUS_next']]
display(data_0)

            LOAN_ID  ASOFMONTH  MBA_DELINQUENCY_STATUS_next
2339640   217166158 2009-12-01                            0
2343048   217166158 2010-01-01                            0
2347941   217166158 2010-02-01                            0
2344680   217166158 2010-03-01                            0
2346282   217166158 2010-04-01                            0
2351332   217166158 2010-05-01                            0
2349733   217166158 2010-06-01                            0
2359832   217166158 2010-07-01                            0
2353088   217166158 2010-08-01                            0
2361551   217166158 2010-09-01                            0
2354782   217166158 2010-10-01                            0
2356432   217166158 2010-11-01                            0
2358053   217166158 2010-12-01                            0
2371625   217166158 2011-01-01                            0
2366488   217166158 2011-02-01                            0
2369851   217166158 2011-03-01                            0
2363083   217166158 2011-04-01                            0
2364728   217166158 2011-05-01                            0
2368112   217166158 2011-06-01                            0
2376162   217166158 2011-07-01                            0
2377764   217166158 2011-08-01                            0
2373006   217166158 2011-09-01                            0
2374550   217166158 2011-10-01                            0
3167058   217166158 2011-11-01                            0
3168548   217166158 2011-12-01                            0
3175878   217166158 2012-01-01                            0
3170007   217166158 2012-02-01                            0
3174389   217166158 2012-03-01                            0
3171468   217166158 2012-04-01                            0
3172923   217166158 2012-05-01                            0
...             ...        ...                          ...
2063221  1232142198 2012-06-01                            4
3156402  1232142198 2012-07-01                            4
3157316  1232142198 2012-08-01                            4
3158226  1232142198 2012-09-01                            4
3159115  1232142198 2012-10-01                            4
3159986  1232142198 2012-11-01                            4
3160857  1232142198 2012-12-01                            4
3161712  1232142198 2013-01-01                            4
3162555  1232142198 2013-02-01                            4
3163367  1232142198 2013-03-01                            4
3164161  1232142198 2013-04-01                            4
3164941  1232142198 2013-05-01                            0
3165656  1232142198 2013-06-01                            0
3763150  1232142198 2013-07-01                            0
3762439  1232142198 2013-08-01                            0
3763846  1232142198 2013-09-01                            0
3764541  1232142198 2013-10-01                            0
3765229  1232142198 2013-11-01                            0
3765913  1232142198 2013-12-01                            0
3767299  1232142198 2014-01-01                            0
3766591  1232142198 2014-02-01                            0
3768688  1232142198 2014-03-01                            0
3767989  1232142198 2014-04-01                            0
3769978  1232142198 2014-05-01                            0
3769301  1232142198 2014-06-01                            0
3771178  1232142198 2014-07-01                            0
3771779  1232142198 2014-08-01                            0
3770577  1232142198 2014-09-01                            0
3772953  1232142198 2014-10-01                            0
3772368  1232142198 2014-11-01                            0

[1032823 rows x 3 columns]

## Function dropping Invalid Delinquencies

This function delete rows in the full dataset that satisfy certain conditions. For example, in case of 0-'Paid-Off', these consecutive states could be considered as invalid when the diference between the months each other is less or equal to 31 days.

In [16]:
def invalid_consecutive_delinquencies (group):
    uw = []
    for i in range(0, (len(group)-1)):        
        if (group.iloc[i+1]['ASOFMONTH'] - group.iloc[i]['ASOFMONTH']) <= datetime.timedelta(days=31):             
            uw.append(i+1)
    
    return group.index[uw]


def drop_invalid_delinquency_status(data, function, status=None):
    # groups = all_data[['LOAN_ID', 'MBA_DELINQUENCY_STATUS_next', 'ASOFMONTH']][all_data['MBA_DELINQUENCY_STATUS_next']==0].groupby(['LOAN_ID', 'MBA_DELINQUENCY_STATUS_next'])
    if status==None:
        groups = data[['LOAN_ID', 'ASOFMONTH', 'MBA_DELINQUENCY_STATUS_next']].groupby(['LOAN_ID'])
    else:
        groups = data[['LOAN_ID', 'ASOFMONTH']][data['MBA_DELINQUENCY_STATUS_next']==status].groupby(['LOAN_ID'])
    iuw = pd.Index([]) # inmutable data structure
    for name, group in groups: # group is a DataFrame
        # print(name) # the whole composed index column: ('LOAN_ID', 'MBA_DELINQUENCY_STATUS_next')
        group = group.sort_values(by=['ASOFMONTH'], ascending=[1])            
        iuw = iuw.union(function(group))        
        
    if iuw!=[]:                        
        data.drop(iuw, inplace=True) #the function update the dataframe inplace.
    
    # return groups.apply(lambda x: x) # to return the DataFrameGroupBy in a DataFrame object.

#### Dropping rows with 0-'Paid-Off' consecutive delinquencies respect to the dates each other

In [17]:
red_data = all_data.copy()
drop_invalid_delinquency_status(red_data, invalid_consecutive_delinquencies, status=0)
display(red_data.shape)

(3831833, 196)

In [19]:
M = markov_tmatrix_per_loan(red_data)
display('Transition Matrix per Loan without consecutive Paid-Off status')
display(M)
display('Probabilities Matrix per Loan without consecutive Paid-Off status')
probabilities_matrix(M)
for row in M: print(' '.join('{0:.3f}'.format(x) for x in row))

'Transition Matrix per Loan without consecutive Paid-Off status'

[[0, 1, 0, 3, 4, 3, 1],
 [637, 33504, 16238, 119, 26030, 13, 2],
 [163, 3743, 9316, 10443, 2558, 798, 1],
 [1312, 788, 1415, 51078, 2701, 8107, 327],
 [34142, 38542, 206, 66, 3442966, 14, 8],
 [1294, 112, 63, 4093, 896, 58475, 1720],
 [368, 3, 0, 468, 9, 72, 7916]]

'Probabilities Matrix per Loan without consecutive Paid-Off status'

0.000 0.083 0.000 0.250 0.333 0.250 0.083
0.008 0.438 0.212 0.002 0.340 0.000 0.000
0.006 0.139 0.345 0.386 0.095 0.030 0.000
0.020 0.012 0.022 0.777 0.041 0.123 0.005
0.010 0.011 0.000 0.000 0.979 0.000 0.000
0.019 0.002 0.001 0.061 0.013 0.877 0.026
0.042 0.000 0.000 0.053 0.001 0.008 0.896

After the dropping task, the dataset already contains some 'Paid-Off' consecutive states which are distant in months but these were not considered in the previous transition matrix calculation. 

From the paper (Sirignano et. al, 2017): 

"REO and paid-oﬀ are treated as absorbing states. That is, we stop tracking the mortgage after the ﬁrst time it enters REO or paid off" ... 

According to this observation, should these states be eliminated??

For example:

In [21]:
groups = red_data[['LOAN_ID', 'MBA_DELINQUENCY_STATUS_next', 'ASOFMONTH']].groupby(['LOAN_ID'])
display(groups.get_group(1152166545))

            LOAN_ID  MBA_DELINQUENCY_STATUS_next  ASOFMONTH
100664   1152166545                            4 2005-04-01
100745   1152166545                            4 2005-05-01
100867   1152166545                            4 2005-06-01
101032   1152166545                            4 2005-07-01
101262   1152166545                            4 2005-08-01
102075   1152166545                            4 2005-09-01
102400   1152166545                            4 2005-10-01
102813   1152166545                            4 2005-11-01
101526   1152166545                            4 2005-12-01
105970   1152166545                            4 2006-01-01
103285   1152166545                            4 2006-02-01
104623   1152166545                            4 2006-03-01
103945   1152166545                            4 2006-04-01
106578   1152166545                            4 2006-05-01
105294   1152166545                            4 2006-06-01
107251   1152166545                            4 2006-07-01
107921   1152166545                            4 2006-08-01
109246   1152166545                            4 2006-09-01
108589   1152166545                            4 2006-10-01
109903   1152166545                            4 2006-11-01
110559   1152166545                            4 2006-12-01
111853   1152166545                            4 2007-01-01
111210   1152166545                            4 2007-02-01
114402   1152166545                            4 2007-03-01
112501   1152166545                            4 2007-04-01
113134   1152166545                            4 2007-05-01
113772   1152166545                            4 2007-06-01
115655   1152166545                            4 2007-07-01
115034   1152166545                            4 2007-08-01
118217   1152166545                            4 2007-09-01
116279   1152166545                            4 2007-10-01
116929   1152166545                            4 2007-11-01
117574   1152166545                            4 2007-12-01
121356   1152166545                            4 2008-01-01
118829   1152166545                            4 2008-02-01
119464   1152166545                            4 2008-03-01
120095   1152166545                            4 2008-04-01
121991   1152166545                            4 2008-05-01
120723   1152166545                            4 2008-06-01
125067   1152166545                            4 2008-07-01
125688   1152166545                            4 2008-08-01
122615   1152166545                            4 2008-09-01
123233   1152166545                            4 2008-10-01
123847   1152166545                            4 2008-11-01
124459   1152166545                            4 2008-12-01
128666   1152166545                            4 2009-01-01
126307   1152166545                            4 2009-02-01
129271   1152166545                            0 2009-03-01
3917227  1152166545                            0 2010-06-01

## Dropping invalid transitions between delinquency statuses:

There are other invalid transitions that are present in our current transition matrix: 
                    - current --> 60,
                    - current -->90,
                    - 30 --> 90,
                    - REO --> any other state?? (except itself??),
                    - PAID-OFF --> any other state?? (except itself??)

From Paper (Sirignano et. al, 2017): 

"Monthly mortgage transitions from current to 60 days delinquent or from 30 days delinquent to 90+ days delinquent 
are not possible. Errors of this type are very infrequent in the dataset and we remove those samples 
where such errors occur."
 
"Certain transitions are not allowed in the dataset (e.g., current to 60 days delinquent).  Although such a transition is theoretically allowed in the formulation (2), the transition probabilities of transitions which do not occur in the dataset will be driven to zero during training." 

Based on this, Should REO --> REO and PAID-OFF --> PAID-OFF be considered as invalid transitions?. After training our model, Is it necessary change the predicted output for invalid transitions in a hard-coded way???.


Tables 8, 9 and 10, extracted from Paper (Sirignano et. al, 2017):
<img src="figures_mtm/monthly_transition_matrix_from_paper.png">

Image extracted from RiskModel_V4_Technical_Document.pdf (CoreLogic Group):

<img src="figures_mtm/all_posible_mortgage_transitions.png">

It can be observed differences between the allowed state transitions by each approach (Sirignano et. al and CoreLogic-Group). Our dataset looks more like Sirignano et. al approach. However, it is important to study these differences to build the most realistic approach for mortgages.

The following function finds the invalid transitions per loan in consecutive months according the previous dissertation:

In [22]:
def invalid_transition (group):
    '''
    Assuming integer labels according with the following dictionary: 
    {'0': 0, '3': 1, '6': 2, '9': 3, 'C': 4, 'F': 5, 'R': 6}
 
    '''
    uw = []
    for i in range(0, (len(group)-1)):        
        if (((group.iloc[i]['MBA_DELINQUENCY_STATUS_next'] == 4) and (group.iloc[i+1]['MBA_DELINQUENCY_STATUS_next'] == 2))             
           or ((group.iloc[i]['MBA_DELINQUENCY_STATUS_next'] == 4) and (group.iloc[i+1]['MBA_DELINQUENCY_STATUS_next'] == 3))
           or ((group.iloc[i]['MBA_DELINQUENCY_STATUS_next'] == 1) and (group.iloc[i+1]['MBA_DELINQUENCY_STATUS_next'] == 3))
           or ((group.iloc[i]['MBA_DELINQUENCY_STATUS_next'] == 0) and (group.iloc[i+1]['MBA_DELINQUENCY_STATUS_next'] != 0))
           or ((group.iloc[i]['MBA_DELINQUENCY_STATUS_next'] == 6) and (group.iloc[i+1]['MBA_DELINQUENCY_STATUS_next'] != 6))): 
            if (group.iloc[i+1]['ASOFMONTH'] - group.iloc[i]['ASOFMONTH']) <= datetime.timedelta(days=31):
                uw.append(i+1)
    return group.index[uw]

For this pruning, it will be used the dataset without 0-'Paid-Off' consecutive status as aforementioned.

In [23]:
drop_invalid_delinquency_status(red_data, invalid_transition, status=None)

After this, the dataset was reduced in 1323 records.

In [24]:
display(red_data.shape)
red_data.to_hdf(os.path.join(pdata_dir, 'reduced_data.h5'), 'table', mode='w')

(3830510, 196)

In [3]:
# to recover and check the results:
# new_data = read_hdf('storage.h5','d1',where=['A>.5'], columns=['A','B'])
red_data = pd.read_hdf(os.path.join(pdata_dir, 'reduced_data.h5'), 'table')
display(red_data)

,LOAN_ID,ASOFMONTH,MBA_DAYS_DELINQUENT,CURRENT_INTEREST_RATE,LLMA2_CURRENT_INTEREST_SPREAD,LOANAGE,CURRENT_BALANCE,SCHEDULED_PRINCIPAL,SCHEDULED_MONTHLY_PANDI,LLMA2_HIST_LAST_12_MONTHS_MIS,...,STATE_VA,STATE_VI,STATE_VT,STATE_WA,STATE_WI,STATE_WV,STATE_WY,STATE,UR,MBA_DELINQUENCY_STATUS_next
3548663,131175200,2005-10-01,0,8.375,2.305,0,67777.656250,45.950001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.6,1
3549190,131175200,2005-11-01,30,8.375,2.045,1,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.5,2
3548834,131175200,2005-12-01,60,8.375,2.105,2,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.4,5
3549381,131175200,2006-01-01,90,8.375,2.225,3,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.4,5
3549637,131175200,2006-02-01,120,8.375,2.125,4,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.3,3
3550739,131175200,2006-03-01,90,8.375,2.055,5,68194.117188,43.040001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.3,3
3549904,131175200,2006-04-01,120,8.375,1.865,6,68194.117188,43.040001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.3,0
1657429,217010733,2011-03-01,0,6.250,1.410,74,67151.031250,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.6,4
1657755,217010733,2011-04-01,0,6.250,1.410,75,66891.906250,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.5,4
1658074,217010733,2011-05-01,0,6.250,1.610,76,66628.671875,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.4,4
1658388,217010733,2011-06-01,0,6.250,1.740,77,66366.828125,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.4,4
1659817,217010733,2011-07-01,0,6.250,1.700,78,66103.632812,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.4,4
1660108,217010733,2011-08-01,0,6.250,1.980,79,65839.062500,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.3,4
1658675,217010733,2011-09-01,0,6.250,2.140,80,65573.109375,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.2,4
1658958,217010733,2011-10-01,0,6.250,2.180,81,65305.781250,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,9.1,4
1659235,217010733,2011-11-01,0,6.250,2.260,82,65037.050781,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.9,4
1659507,217010733,2011-12-01,0,6.250,2.290,83,64766.921875,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.7,4
1661680,217010733,2012-01-01,0,6.250,2.330,84,64495.390625,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.4,4
1660904,217010733,2012-02-01,0,6.250,2.360,85,64222.441406,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1660364,217010733,2012-03-01,0,6.250,2.300,86,63948.070312,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1660631,217010733,2012-04-01,0,6.250,2.340,87,63672.269531,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1661164,217010733,2012-05-01,0,6.250,2.450,88,63395.039062,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1661408,217010733,2012-06-01,0,6.250,2.570,89,63116.359375,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1661906,217010733,2012-07-01,0,6.250,2.700,90,62836.230469,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1662143,217010733,2012-08-01,0,6.250,2.650,91,62271.589844,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1662375,217010733,2012-09-01,0,6.250,2.750,92,62271.589844,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1662605,217010733,2012-10-01,0,6.250,2.870,93,61986.269531,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1662833,217010733,2012-11-01,0,6.250,2.900,94,61700.199219,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1663079,217010733,2012-12-01,0,6.250,2.900,95,61412.640625,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1663322,217010733,2013-01-01,0,6.250,2.840,96,61123.578125,0.000000,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3834281,1243775877,2014-07-01,0,0.046,-4.084,103,88342.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.8,4
3833750,1243775877,2014-08-01,0,0.046,-4.074,104,88270.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.8,4
3834011,1243775877,2014-09-01,0,0.046,-4.114,105,88198.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.7,4
3834542,1243775877,2014-10-01,0,0.046,-3.994,106,88125.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.7,4
3834802,1243775877,2014-11-01,0,0.046,-3.954,107,88052.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.6,4
3149484,1243775964,2012-11-01,30,0.069,-3.281,82,124085.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3149813,1243775964,2012-12-01,30,0.069,-3.281,83,123903.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3150138,1243775964,2013-01-01,30,0.069,-3.341,84,123719.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3151014,1243775964,2013-02-01,30,0.069,-3.461,85,123534.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3150421,1243775964,2013-03-01,30,0.069,-3.501,86,123349.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3150692,1243775964,2013-04-01,30,0.069,-3.381,87,123162.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.8,1
3151534,1243775964,2013-05-01,30,0.069,-3.471,88,122974.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.8,1
3151242,1243775964,2013-06-01,30,0.069,-4.001,89,122785.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.7,1
3152041,1243775964,2013-07-01,30,0.069,-4.301,90,122595.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.6,2
3151779,1243775964,2013-08-01,60,0.069,-4.391,91,122595.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.6,2
3152549,1243775964,2013-09-01,60,0.069,-4.421,92,122404.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.5,2
3153054,1243775964,2013-10-01,60,0.069,-4.121,93,122212.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.4,3
3152290,1243775964,2013-11-01,90,0.069,-4.191,94,122212.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.3,1
3152800,1243775964,2013-12-01,30,0.069,-4.391,95,121629.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.1,1
3153550,1243775964,2014-01-01,30,0.069,-4.361,96,121432.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.0,1
3153295,1243775964,2014-02-01,30,0.069,-4.231,97,121235.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.8,1
3153797,1243775964,2014-03-01,30,0.069,-4.271,98,121036.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.7,1
3154037,1243775964,2014-04-01,30,0.069,-4.271,99,120836.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.6,4
3154277,1243775964,2014-05-01,0,0.069,-4.121,100,120432.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.5,4
3154484,1243775964,2014-06-01,0,0.069,-4.091,101,120229.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.4,4
3155089,1243775964,2014-07-01,0,0.069,-4.061,102,119980.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.3,4
3154688,1243775964,2014-08-01,0,0.069,-4.051,103,119729.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.2,4
3155289,1243775964,2014-09-01,0,0.069,-4.091,104,119477.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.1,4
3154886,1243775964,2014-10-01,0,0.069,-3.971,105,119268.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.0,4
3155487,1243775964,2014-11-01,0,0.069,-3.931,106,119058.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,4.9,4

Calculating the Transition Matrix.

In [8]:
M = markov_tmatrix_per_loan(red_data)
display('Transition Matrix per Loan without invalid transitions and consecutive Paid-Off status')
display(M)
display('Probabilities Matrix per Loan without invalid transitions and consecutive Paid-Off status')
probabilities_matrix(M)
for row in M: print(' '.join('{0:.3f}'.format(x) for x in row))

'Transition Matrix per Loan without invalid transitions and consecutive Paid-Off status'

[[0, 0, 0, 0, 0, 0, 0],
 [636, 33502, 16238, 0, 26029, 13, 2],
 [160, 3701, 9266, 10387, 2512, 794, 1],
 [1172, 780, 1398, 50687, 2665, 8066, 327],
 [34142, 38542, 0, 0, 3442954, 14, 8],
 [1292, 112, 63, 4089, 896, 58407, 1719],
 [0, 0, 0, 0, 0, 0, 7915]]

'Probabilities Matrix per Loan without invalid transitions and consecutive Paid-Off status'

0.000 0.000 0.000 0.000 0.000 0.000 0.000
0.008 0.438 0.212 0.000 0.341 0.000 0.000
0.006 0.138 0.345 0.387 0.094 0.030 0.000
0.018 0.012 0.021 0.779 0.041 0.124 0.005
0.010 0.011 0.000 0.000 0.979 0.000 0.000
0.019 0.002 0.001 0.061 0.013 0.877 0.026
0.000 0.000 0.000 0.000 0.000 0.000 1.000

## Transition Matrix for subprime/prime datasets.

In [9]:
display(red_data[red_data['LLMA2_SUBPRIME']==1])

,LOAN_ID,ASOFMONTH,MBA_DAYS_DELINQUENT,CURRENT_INTEREST_RATE,LLMA2_CURRENT_INTEREST_SPREAD,LOANAGE,CURRENT_BALANCE,SCHEDULED_PRINCIPAL,SCHEDULED_MONTHLY_PANDI,LLMA2_HIST_LAST_12_MONTHS_MIS,...,STATE_VA,STATE_VI,STATE_VT,STATE_WA,STATE_WI,STATE_WV,STATE_WY,STATE,UR,MBA_DELINQUENCY_STATUS_next
3548663,131175200,2005-10-01,0,8.375,2.305,0,67777.656250,45.950001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.6,1
3549190,131175200,2005-11-01,30,8.375,2.045,1,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.5,2
3548834,131175200,2005-12-01,60,8.375,2.105,2,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.4,5
3549381,131175200,2006-01-01,90,8.375,2.225,3,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.4,5
3549637,131175200,2006-02-01,120,8.375,2.125,4,68279.289062,42.450001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.3,3
3550739,131175200,2006-03-01,90,8.375,2.055,5,68194.117188,43.040001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.3,3
3549904,131175200,2006-04-01,120,8.375,1.865,6,68194.117188,43.040001,518.969971,0,...,0,0,0,0,0,0,0,NH,3.3,0
2339640,217166158,2009-12-01,0,8.500,3.570,57,0.000000,0.000000,0.000000,1,...,0,0,0,0,0,0,0,IL,11.2,0
1804636,217236823,2005-04-01,0,6.500,0.640,1,201234.515625,0.000000,1274.250000,1,...,0,0,0,0,0,0,0,NJ,4.3,4
1805236,217236823,2005-05-01,0,6.500,0.780,2,200051.281250,0.000000,1274.250000,1,...,0,0,0,0,0,0,0,NJ,4.2,4
1804817,217236823,2005-06-01,0,6.500,0.920,3,200051.281250,0.000000,1274.250000,1,...,0,0,0,0,0,0,0,NJ,4.2,4
1804644,217241915,2005-04-01,0,6.875,1.015,1,399663.937500,0.000000,2627.709961,1,...,0,0,0,0,0,0,0,NJ,4.3,4
1805244,217241915,2005-05-01,0,6.875,1.155,2,399325.968750,0.000000,2627.709961,1,...,0,0,0,0,0,0,0,NJ,4.2,4
1804825,217241915,2005-06-01,0,6.875,1.295,3,398644.187500,0.000000,2627.709961,1,...,0,0,0,0,0,0,0,NJ,4.2,4
1785078,217322232,2011-03-01,180,9.000,4.160,71,84084.523438,61.490002,691.619995,1,...,0,0,0,0,0,0,0,OH,9.0,0
323746,217647229,2005-08-01,0,6.125,0.305,3,266217.500000,0.000000,1622.319946,1,...,0,0,0,0,0,0,0,CA,5.3,4
1871386,217861385,2005-11-01,0,7.900,1.570,4,148387.046875,104.620003,1081.489990,1,...,0,0,0,0,0,0,0,MO,5.0,4
1869756,217861385,2005-12-01,0,7.900,1.630,5,148281.078125,105.320000,1081.489990,1,...,0,0,0,0,0,0,0,MO,5.0,4
1872107,217861385,2006-01-01,0,7.900,1.750,6,148175.765625,106.010002,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.9,4
1873027,217861385,2006-02-01,0,7.900,1.650,7,148068.421875,106.720001,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.9,4
1875008,217861385,2006-03-01,0,7.900,1.580,8,147961.703125,107.419998,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.8,4
1874008,217861385,2006-04-01,0,7.900,1.390,9,147850.671875,108.150002,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.7,4
1876995,217861385,2006-05-01,0,7.900,1.300,10,147742.265625,108.860001,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.8,4
1876005,217861385,2006-06-01,0,7.900,1.220,11,147633.406250,109.580002,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.8,4
1878958,217861385,2006-07-01,0,7.900,1.140,12,147523.515625,110.300003,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.9,4
1877988,217861385,2006-08-01,0,7.900,1.380,13,147413.234375,111.029999,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.9,4
1880883,217861385,2006-09-01,0,7.900,1.500,14,147302.203125,111.760002,1081.489990,1,...,0,0,0,0,0,0,0,MO,5.0,4
1879936,217861385,2006-10-01,0,7.900,1.540,15,147190.453125,112.500000,1081.489990,1,...,0,0,0,0,0,0,0,MO,5.0,4
1881815,217861385,2006-11-01,0,7.900,1.660,16,147077.968750,113.239998,1081.489990,1,...,0,0,0,0,0,0,0,MO,5.0,4
1882769,217861385,2006-12-01,0,7.900,1.760,17,146957.421875,114.029999,1081.489990,1,...,0,0,0,0,0,0,0,MO,4.9,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3834281,1243775877,2014-07-01,0,0.046,-4.084,103,88342.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.8,4
3833750,1243775877,2014-08-01,0,0.046,-4.074,104,88270.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.8,4
3834011,1243775877,2014-09-01,0,0.046,-4.114,105,88198.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.7,4
3834542,1243775877,2014-10-01,0,0.046,-3.994,106,88125.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.7,4
3834802,1243775877,2014-11-01,0,0.046,-3.954,107,88052.000000,0.000000,637.000000,0,...,0,0,0,0,0,0,0,IN,5.6,4
3149484,1243775964,2012-11-01,30,0.069,-3.281,82,124085.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3149813,1243775964,2012-12-01,30,0.069,-3.281,83,123903.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3150138,1243775964,2013-01-01,30,0.069,-3.341,84,123719.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3151014,1243775964,2013-02-01,30,0.069,-3.461,85,123534.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3150421,1243775964,2013-03-01,30,0.069,-3.501,86,123349.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.9,1
3150692,1243775964,2013-04-01,30,0.069,-3.381,87,123162.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.8,1
3151534,1243775964,2013-05-01,30,0.069,-3.471,88,122974.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.8,1
3151242,1243775964,2013-06-01,30,0.069,-4.001,89,122785.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.7,1
3152041,1243775964,2013-07-01,30,0.069,-4.301,90,122595.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.6,2
3151779,1243775964,2013-08-01,60,0.069,-4.391,91,122595.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.6,2
3152549,1243775964,2013-09-01,60,0.069,-4.421,92,122404.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.5,2
3153054,1243775964,2013-10-01,60,0.069,-4.121,93,122212.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.4,3
3152290,1243775964,2013-11-01,90,0.069,-4.191,94,122212.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.3,1
3152800,1243775964,2013-12-01,30,0.069,-4.391,95,121629.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.1,1
3153550,1243775964,2014-01-01,30,0.069,-4.361,96,121432.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,6.0,1
3153295,1243775964,2014-02-01,30,0.069,-4.231,97,121235.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.8,1
3153797,1243775964,2014-03-01,30,0.069,-4.271,98,121036.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.7,1
3154037,1243775964,2014-04-01,30,0.069,-4.271,99,120836.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.6,4
3154277,1243775964,2014-05-01,0,0.069,-4.121,100,120432.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.5,4
3154484,1243775964,2014-06-01,0,0.069,-4.091,101,120229.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.4,4
3155089,1243775964,2014-07-01,0,0.069,-4.061,102,119980.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.3,4
3154688,1243775964,2014-08-01,0,0.069,-4.051,103,119729.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.2,4
3155289,1243775964,2014-09-01,0,0.069,-4.091,104,119477.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.1,4
3154886,1243775964,2014-10-01,0,0.069,-3.971,105,119268.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,5.0,4
3155487,1243775964,2014-11-01,0,0.069,-3.931,106,119058.000000,0.000000,893.880005,0,...,0,0,0,0,1,0,0,WI,4.9,4

In [11]:
subprime_data = red_data[red_data['LLMA2_SUBPRIME']==1]
M = markov_tmatrix_per_loan(subprime_data)
display('Transition Matrix per SUBPRIME Loan without invalid transitions and consecutive Paid-Off status')
display(M)
display('Probabilities Matrix per SUBPRIME Loan without invalid transitions and consecutive Paid-Off status')
probabilities_matrix(M)
for row in M: print(' '.join('{0:.3f}'.format(x) for x in row))

'Transition Matrix per SUBPRIME Loan without invalid transitions and consecutive Paid-Off status'

[[0, 0, 0, 0, 0, 0, 0],
 [140, 9935, 3813, 0, 6251, 2, 0],
 [40, 1171, 2623, 2224, 689, 121, 0],
 [128, 232, 423, 10216, 647, 1487, 39],
 [1991, 8832, 0, 0, 236993, 4, 3],
 [267, 28, 15, 738, 248, 9285, 228],
 [0, 0, 0, 0, 0, 0, 1543]]

'Probabilities Matrix per SUBPRIME Loan without invalid transitions and consecutive Paid-Off status'

0.000 0.000 0.000 0.000 0.000 0.000 0.000
0.007 0.493 0.189 0.000 0.310 0.000 0.000
0.006 0.171 0.382 0.324 0.100 0.018 0.000
0.010 0.018 0.032 0.776 0.049 0.113 0.003
0.008 0.036 0.000 0.000 0.956 0.000 0.000
0.025 0.003 0.001 0.068 0.023 0.859 0.021
0.000 0.000 0.000 0.000 0.000 0.000 1.000

In [12]:
display(red_data[red_data['LLMA2_PRIME']==1])

,LOAN_ID,ASOFMONTH,MBA_DAYS_DELINQUENT,CURRENT_INTEREST_RATE,LLMA2_CURRENT_INTEREST_SPREAD,LOANAGE,CURRENT_BALANCE,SCHEDULED_PRINCIPAL,SCHEDULED_MONTHLY_PANDI,LLMA2_HIST_LAST_12_MONTHS_MIS,...,STATE_VA,STATE_VI,STATE_VT,STATE_WA,STATE_WI,STATE_WV,STATE_WY,STATE,UR,MBA_DELINQUENCY_STATUS_next
1657429,217010733,2011-03-01,0,6.250,1.410,74,67151.031250,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.6,4
1657755,217010733,2011-04-01,0,6.250,1.410,75,66891.906250,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.5,4
1658074,217010733,2011-05-01,0,6.250,1.610,76,66628.671875,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.4,4
1658388,217010733,2011-06-01,0,6.250,1.740,77,66366.828125,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.4,4
1659817,217010733,2011-07-01,0,6.250,1.700,78,66103.632812,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.4,4
1660108,217010733,2011-08-01,0,6.250,1.980,79,65839.062500,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.3,4
1658675,217010733,2011-09-01,0,6.250,2.140,80,65573.109375,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.2,4
1658958,217010733,2011-10-01,0,6.250,2.180,81,65305.781250,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,9.1,4
1659235,217010733,2011-11-01,0,6.250,2.260,82,65037.050781,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.9,4
1659507,217010733,2011-12-01,0,6.250,2.290,83,64766.921875,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.7,4
1661680,217010733,2012-01-01,0,6.250,2.330,84,64495.390625,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.4,4
1660904,217010733,2012-02-01,0,6.250,2.360,85,64222.441406,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1660364,217010733,2012-03-01,0,6.250,2.300,86,63948.070312,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1660631,217010733,2012-04-01,0,6.250,2.340,87,63672.269531,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1661164,217010733,2012-05-01,0,6.250,2.450,88,63395.039062,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1661408,217010733,2012-06-01,0,6.250,2.570,89,63116.359375,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1661906,217010733,2012-07-01,0,6.250,2.700,90,62836.230469,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1662143,217010733,2012-08-01,0,6.250,2.650,91,62271.589844,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1662375,217010733,2012-09-01,0,6.250,2.750,92,62271.589844,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.2,4
1662605,217010733,2012-10-01,0,6.250,2.870,93,61986.269531,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1662833,217010733,2012-11-01,0,6.250,2.900,94,61700.199219,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1663079,217010733,2012-12-01,0,6.250,2.900,95,61412.640625,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1663322,217010733,2013-01-01,0,6.250,2.840,96,61123.578125,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1663555,217010733,2013-02-01,0,6.250,2.720,97,60833.070312,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1663771,217010733,2013-03-01,0,6.250,2.680,98,60541.050781,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1663979,217010733,2013-04-01,0,6.250,2.800,99,60247.511719,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1664380,217010733,2013-05-01,0,6.250,2.710,100,59948.718750,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1664158,217010733,2013-06-01,0,6.250,2.180,101,59652.089844,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1664775,217010733,2013-07-01,0,6.250,1.880,102,59353.921875,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
1664573,217010733,2013-08-01,0,6.250,1.790,103,59054.199219,0.0,608.859985,1,...,0,0,0,0,0,0,0,KY,8.1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1522720,1243620758,2013-09-01,0,0.059,-4.431,93,220068.000000,0.0,1479.000000,0,...,0,0,0,0,0,0,0,CA,8.6,4
1525035,1243620758,2013-10-01,0,0.059,-4.131,94,219667.000000,0.0,1479.000000,0,...,0,0,0,0,0,0,0,CA,8.5,4
1529593,1243620758,2013-11-01,0,0.059,-4.201,95,219263.000000,0.0,1479.000000,0,...,0,0,0,0,0,0,0,CA,8.3,4
1527304,1243620758,2013-12-01,0,0.059,-4.401,96,218858.000000,0.0,1479.000000,0,...,0,0,0,0,0,0,0,CA,8.2,4
1534156,1243620758,2014-01-01,0,0.059,-4.371,97,218451.000000,0.0,1479.000000,0,...,0,0,0,0,0,0,0,CA,8.1,0
3160058,1243623593,2012-11-01,0,0.063,-3.287,87,37232.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.8,4
3160929,1243623593,2012-12-01,0,0.063,-3.287,88,36778.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.8,4
3161783,1243623593,2013-01-01,0,0.063,-3.347,89,36549.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.8,4
3162625,1243623593,2013-02-01,0,0.063,-3.467,90,36320.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.8,4
3163436,1243623593,2013-03-01,0,0.063,-3.507,91,36089.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.7,4
3164229,1243623593,2013-04-01,0,0.063,-3.387,92,36089.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.7,4
3165009,1243623593,2013-05-01,0,0.063,-3.477,93,35623.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.6,4
3165721,1243623593,2013-06-01,0,0.063,-4.007,94,35389.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.6,4
3763214,1243623593,2013-07-01,0,0.063,-4.307,95,35389.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.5,4
3762503,1243623593,2013-08-01,0,0.063,-4.397,96,34896.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.5,4
3763910,1243623593,2013-09-01,0,0.063,-4.427,97,34896.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.5,4
3764605,1243623593,2013-10-01,0,0.063,-4.127,98,34378.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.4,4
3765291,1243623593,2013-11-01,0,0.063,-4.197,99,34117.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.3,4
3765975,1243623593,2013-12-01,0,0.063,-4.397,100,33855.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.2,4
3767360,1243623593,2014-01-01,0,0.063,-4.367,101,33591.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.1,4
3766650,1243623593,2014-02-01,0,0.063,-4.237,102,33591.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.0,4
3768746,1243623593,2014-03-01,0,0.063,-4.277,103,33326.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,7.0,4
3768047,1243623593,2014-04-01,0,0.063,-4.277,104,32791.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.9,4
3770036,1243623593,2014-05-01,0,0.063,-4.127,105,32791.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.8,4
3769356,1243623593,2014-06-01,0,0.063,-4.097,106,32522.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.7,4
3771232,1243623593,2014-07-01,0,0.063,-4.067,107,31979.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.6,4
3771833,1243623593,2014-08-01,0,0.063,-4.057,108,31979.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.6,4
3770631,1243623593,2014-09-01,0,0.063,-4.097,109,31701.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.5,4
3773005,1243623593,2014-10-01,0,0.063,-3.977,110,31140.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.5,4
3772420,1243623593,2014-11-01,0,0.063,-3.937,111,30857.000000,0.0,380.000000,0,...,0,0,0,0,0,0,0,AZ,6.4,4

In [14]:
prime_data = red_data[red_data['LLMA2_PRIME']==1]
M = markov_tmatrix_per_loan(prime_data)
display('Transition Matrix per PRIME Loan without invalid transitions and consecutive Paid-Off status')
display(M)
display('Probabilities Matrix per PRIME Loan without invalid transitions and consecutive Paid-Off status')
probabilities_matrix(M)
for row in M: print(' '.join('{0:.3f}'.format(x) for x in row))

'Transition Matrix per PRIME Loan without invalid transitions and consecutive Paid-Off status'

[[0, 0, 0, 0, 0, 0, 0],
 [491, 23340, 12270, 0, 19612, 11, 2],
 [120, 2504, 6576, 8051, 1809, 664, 1],
 [1020, 542, 960, 39864, 1991, 6498, 285],
 [31753, 29420, 0, 0, 3173264, 10, 5],
 [1011, 84, 48, 3305, 644, 48584, 1474],
 [0, 0, 0, 0, 0, 0, 6266]]

'Probabilities Matrix per PRIME Loan without invalid transitions and consecutive Paid-Off status'

0.000 0.000 0.000 0.000 0.000 0.000 0.000
0.009 0.419 0.220 0.000 0.352 0.000 0.000
0.006 0.127 0.333 0.408 0.092 0.034 0.000
0.020 0.011 0.019 0.779 0.039 0.127 0.006
0.010 0.009 0.000 0.000 0.981 0.000 0.000
0.018 0.002 0.001 0.060 0.012 0.881 0.027
0.000 0.000 0.000 0.000 0.000 0.000 1.000

The transition matrices for Prime, SubPrime and the full dataset looks quite similiar to the results shown above by Sirignano et. al, 2017 at tables 8, 9 and 10 except for the Paid-Off status.

## Loans that do not belong to Prime/Subprime types

What kind of loan the following records belongs??

In [15]:
u_data =red_data[(red_data['LLMA2_PRIME']==0) & (red_data['LLMA2_SUBPRIME']==0)]
display(u_data)

,LOAN_ID,ASOFMONTH,MBA_DAYS_DELINQUENT,CURRENT_INTEREST_RATE,LLMA2_CURRENT_INTEREST_SPREAD,LOANAGE,CURRENT_BALANCE,SCHEDULED_PRINCIPAL,SCHEDULED_MONTHLY_PANDI,LLMA2_HIST_LAST_12_MONTHS_MIS,...,STATE_VA,STATE_VI,STATE_VT,STATE_WA,STATE_WI,STATE_WV,STATE_WY,STATE,UR,MBA_DELINQUENCY_STATUS_next
2556733,217237944,2005-05-01,0,6.500,0.780,1,463158.78125,0.000000,2932.800049,1,...,0,0,0,0,0,0,0,NY,4.9,4
2556285,217237944,2005-06-01,0,6.500,0.920,2,462734.78125,0.000000,2932.800049,1,...,0,0,0,0,0,0,0,NY,4.9,4
2562348,217644570,2005-08-01,0,6.500,0.680,3,452512.71875,0.000000,2868.010010,1,...,0,0,0,0,0,0,0,NY,5.0,4
323749,218223011,2005-08-01,0,6.000,0.180,1,499502.25000,0.000000,2997.750000,1,...,0,0,0,0,0,0,0,CA,5.3,4
1806138,218232883,2005-08-01,0,6.375,0.555,0,451581.37500,0.000000,2819.899902,1,...,0,0,0,0,0,0,0,NJ,4.4,4
2557163,218737965,2005-10-01,30,5.875,-0.195,2,422069.25000,0.000000,2499.250000,1,...,0,0,0,0,0,0,0,NY,5.0,4
2559717,218737965,2005-11-01,0,5.875,-0.455,3,421201.37500,0.000000,2499.250000,1,...,0,0,0,0,0,0,0,NY,5.0,4
857188,218848629,2009-12-01,180,6.625,1.695,52,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,11.2,5
869301,218848629,2010-01-01,180,6.625,1.595,53,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,11.2,5
873311,218848629,2010-02-01,180,6.625,1.635,54,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,11.1,5
877310,218848629,2010-03-01,180,6.625,1.655,55,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,11.0,5
885298,218848629,2010-04-01,180,6.625,1.525,56,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.9,5
889260,218848629,2010-05-01,180,6.625,1.735,57,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.8,5
881316,218848629,2010-06-01,180,6.625,1.885,58,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.8,5
900957,218848629,2010-07-01,180,6.625,2.065,59,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.8,5
893145,218848629,2010-08-01,180,6.625,2.195,60,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.8,5
897008,218848629,2010-09-01,180,6.625,2.275,61,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.9,5
936998,218848629,2010-10-01,180,6.625,2.395,62,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.9,5
944162,218848629,2010-11-01,180,6.625,2.325,63,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.8,5
940561,218848629,2010-12-01,180,6.625,1.915,64,999723.93750,0.000000,5519.310059,1,...,0,0,0,0,0,0,0,FL,10.7,5
597967,218848636,2009-12-01,180,6.125,1.195,52,393271.50000,0.000000,2007.319946,1,...,0,0,0,0,0,0,0,CA,12.1,3
602769,218848636,2010-01-01,180,6.125,1.095,53,393271.50000,0.000000,2007.319946,1,...,0,0,0,0,0,0,0,CA,12.1,3
607523,218848636,2010-02-01,180,6.125,1.135,54,393271.50000,0.000000,2007.319946,1,...,0,0,0,0,0,0,0,CA,12.2,3
1373340,218848636,2010-03-01,180,6.125,1.155,55,393271.50000,0.000000,2007.319946,1,...,0,0,0,0,0,0,0,CA,12.2,3
1378004,218848636,2010-04-01,180,6.125,1.025,56,393271.50000,0.000000,2007.319946,1,...,0,0,0,0,0,0,0,CA,12.2,3
1387366,218848636,2010-05-01,180,6.125,1.235,57,393271.50000,0.000000,2007.319946,1,...,0,0,0,0,0,0,0,CA,12.1,3
1382732,218848636,2010-06-01,180,6.125,1.385,58,393271.50000,0.000000,2007.319946,1,...,0,0,0,0,0,0,0,CA,12.1,4
1392035,218848636,2010-07-01,0,2.000,-2.560,59,426380.09375,0.000000,1389.770020,1,...,0,0,0,0,0,0,0,CA,12.1,4
1405525,218848636,2010-08-01,0,2.000,-2.430,60,426380.09375,0.000000,1389.770020,1,...,0,0,0,0,0,0,0,CA,12.1,4
1396600,218848636,2010-09-01,0,2.000,-2.350,61,425700.96875,0.000000,1389.770020,1,...,0,0,0,0,0,0,0,CA,12.2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481865,1231981864,2012-06-01,0,5.500,1.820,85,349260.40625,664.700012,2265.479980,0,...,0,0,0,0,0,0,0,CA,10.4,4
1484968,1231981864,2012-07-01,0,5.500,1.950,86,348548.81250,667.750000,2265.479980,0,...,0,0,0,0,0,0,0,CA,10.3,4
1491081,1231981864,2012-08-01,0,5.500,1.900,87,347881.00000,671.030029,2265.479980,0,...,0,0,0,0,0,0,0,CA,10.1,1
1487985,1231981864,2012-09-01,30,5.500,2.000,88,347881.00000,674.099976,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.9,4
1494026,1231981864,2012-10-01,0,5.500,2.120,89,346422.59375,677.190002,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.8,4
1499809,1231981864,2012-11-01,0,5.500,2.150,90,345745.12500,680.820007,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.7,4
1496878,1231981864,2012-12-01,0,5.500,2.150,91,345064.34375,683.940002,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.6,1
1513242,1231981864,2013-01-01,30,5.500,2.090,92,345064.34375,687.070007,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.5,4
1505250,1231981864,2013-02-01,0,5.500,1.970,93,343693.31250,690.219971,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.3,1
1502477,1231981864,2013-03-01,30,5.500,1.930,94,343693.31250,693.380005,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.2,1
1507832,1231981864,2013-04-01,30,5.500,2.050,95,343003.09375,696.559998,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.1,1
1510371,1231981864,2013-05-01,30,5.500,1.960,96,342309.71875,699.750000,2265.479980,0,...,0,0,0,0,0,0,0,CA,9.0,2
1515575,1231981864,2013-06-01,60,5.500,1.430,97,342309.71875,702.960022,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.9,4
1520302,1231981864,2013-07-01,0,5.500,1.130,98,340210.43750,706.179993,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.8,4
1517913,1231981864,2013-08-01,0,5.500,1.040,99,339504.28125,709.419983,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.7,4
1522614,1231981864,2013-09-01,0,5.500,1.010,100,338794.84375,712.669983,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.6,4
1524929,1231981864,2013-10-01,0,5.500,1.310,101,338082.18750,715.940002,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.5,4
1529487,1231981864,2013-11-01,0,5.500,1.240,102,337366.25000,719.219971,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.3,4
1527199,1231981864,2013-12-01,0,5.500,1.040,103,336647.03125,722.510010,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.2,4
1534052,1231981864,2014-01-01,0,5.500,1.070,104,335924.50000,725.830017,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.1,1
1538643,1231981864,2014-02-01,30,5.500,1.200,105,335924.50000,729.150024,2265.479980,0,...,0,0,0,0,0,0,0,CA,8.0,4
1531728,1231981864,2014-03-01,0,5.500,1.160,106,334469.53125,732.489990,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.9,4
1536310,1231981864,2014-04-01,0,5.500,1.160,107,333737.03125,735.849976,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.7,4
1540878,1231981864,2014-05-01,0,5.500,1.310,108,333001.18750,739.219971,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.6,4
1542937,1231981864,2014-06-01,0,5.500,1.340,109,332261.96875,742.609985,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.5,4
1546995,1231981864,2014-07-01,0,5.500,1.370,110,331519.37500,746.020020,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.4,4
1549026,1231981864,2014-08-01,0,5.500,1.380,111,330773.34375,749.440002,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.3,4
1544950,1231981864,2014-09-01,0,5.500,1.340,112,330023.90625,752.869995,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.2,4
1552993,1231981864,2014-10-01,0,5.500,1.460,113,329271.03125,756.320007,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.1,4
1551008,1231981864,2014-11-01,0,5.500,1.500,114,328514.71875,759.789978,2265.479980,0,...,0,0,0,0,0,0,0,CA,7.0,4

In [16]:
gbu_data = u_data[['LOAN_ID', 'ASOFMONTH']].groupby('LOAN_ID').count()
gbu_data

            ASOFMONTH
LOAN_ID
217237944           2
217644570           1
218223011           1
218232883           1
218737965           2
218848629          13
218848636          13
218848785          13
219089093          13
219089140          13
219101040           2
219387189           1
219711839           1
219733456           1
220302093          38
224635377           7
225697860          16
225717822          16
226765091          15
227476099          11
227887632           8
1151097806         82
1151098562         29
1151106191          9
1151121938         35
1151144189         63
1151146167         65
1151153115         74
1152057393         54
1152299292         12
...               ...
1227173128         17
1227173242         17
1227173514         17
1227173544         17
1227173604         17
1227234452          8
1227247909          7
1227251513         19
1227253607         19
1227257270         19
1227318945         19
1227780990          2
1227783479         18
1227783586         18
1227787093          6
1227789434          4
1227792040         18
1228874082         16
1228874676         16
1228897049          9
1228899645          9
1228952816          4
1228953502          9
1228954843         16
1229848568         13
1231211375         17
1231321387          3
1231364622         17
1231485944         13
1231981864         36

[884 rows x 1 columns]

In [17]:
red_data.drop(u_data.index, inplace=True)

The following instructions try to find the unknown typed records inside the full dataset in order to see if there was incorrect labeling, but the results show a empty dataframe:

In [18]:
display(red_data.shape)
display(red_data[red_data['LOAN_ID'].isin(u_data['LOAN_ID'])][['LOAN_ID', 'ASOFMONTH', 'MBA_DELINQUENCY_STATUS_next']])

(3793876, 196)

Empty DataFrame
Columns: [LOAN_ID, ASOFMONTH, MBA_DELINQUENCY_STATUS_next]
Index: []

## Transition Matrix for unknown type of loans

In [19]:
M = markov_tmatrix_per_loan(u_data)
display('Transition Matrix per Unknown type of Loans without invalid transitions and consecutive Paid-Off status')
display(M)
display('Probabilities Matrix per Unknown type of Loans without invalid transitions and consecutive Paid-Off status')
probabilities_matrix(M)
for row in M: print(' '.join('{0:.3f}'.format(x) for x in row))

'Transition Matrix per Unknown type of Loans without invalid transitions and consecutive Paid-Off status'

[[0, 0, 0, 0, 0, 0, 0],
 [5, 227, 155, 0, 166, 0, 0],
 [0, 26, 67, 112, 14, 9, 0],
 [24, 6, 15, 607, 27, 81, 3],
 [398, 290, 0, 0, 32697, 0, 0],
 [14, 0, 0, 46, 4, 538, 17],
 [0, 0, 0, 0, 0, 0, 106]]

'Probabilities Matrix per Unknown type of Loans without invalid transitions and consecutive Paid-Off status'

0.000 0.000 0.000 0.000 0.000 0.000 0.000
0.009 0.410 0.280 0.000 0.300 0.000 0.000
0.000 0.114 0.294 0.491 0.061 0.039 0.000
0.031 0.008 0.020 0.796 0.035 0.106 0.004
0.012 0.009 0.000 0.000 0.979 0.000 0.000
0.023 0.000 0.000 0.074 0.006 0.869 0.027
0.000 0.000 0.000 0.000 0.000 0.000 1.000

How these type of loans should be treated?

### Summarizing Open Questions
The dataset already contains some 'Paid-Off' consecutive states which are distant in months, should these states be eliminated??. 

Should REO --> REO, PAID-OFF --> PAID-OFF, REO --> any other state, PAID-OFF --> any other state be considered as invalid transitions?. 

After training our model, Is it necessary change the predicted output for invalid transitions in a hard-coded way???.

How Loans that do not belong to Prime/Subprime types should be treated??